version: "3.3"
services:
  json-server:
    image: vimagick/json-server
    command: -h 0.0.0.0 -p 3000 -s ./public db.json
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    restart: unless-stopped
